### ISSUE TITLE
Site is 404

### ISSUE THREAD

**Issue by Zireael07** [Nallantli/Sono#1]
**Describe the bug**
Site is 404

**To Reproduce**
Click link in repo

**Expected behavior**
Sono site opens

**Comment by Nallantli** [comment]
I'm not sure how you came across this project, but I'm happy it's of interest to you!

Truth be told, the project has been out of commission for a while now and the original domain is out of service. I went ahead and updated some of the websocketing stuff (although the cert files aren't working for some reason, so for now it's http only) and put it on a new domain at `sono.nallant.li`.

**Comment by Zireael07** [comment]
I am a programmer and a linguist both, and I've seen mention of "a phonology focused scripting language" on this or that list of new scripting languages ;)

**Comment by Nallantli** [comment]
In that case I hope you enjoy my old university project!
